In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv("C:/Users/mail2/Desktop/Sharli/datasets/fraudTrain.csv")
df = pd.DataFrame(train_data)
print(df)

         Unnamed: 0 trans_date_trans_time               cc_num  \
0                 0   2019-01-01 00:00:18     2703186189652095
1                 1   2019-01-01 00:00:44         630423337322
2                 2   2019-01-01 00:00:51       38859492057661
3                 3   2019-01-01 00:01:16     3534093764340240
4                 4   2019-01-01 00:03:06      375534208663984
...             ...                   ...                  ...
1296670     1296670   2020-06-21 12:12:08       30263540414123
1296671     1296671   2020-06-21 12:12:19     6011149206456997
1296672     1296672   2020-06-21 12:12:32     3514865930894695
1296673     1296673   2020-06-21 12:13:36     2720012583106919
1296674     1296674   2020-06-21 12:13:37  4292902571056973207

                                    merchant       category     amt  \
0                 fraud_Rippin, Kub and Mann       misc_net    4.97
1            fraud_Heller, Gutmann and Zieme    grocery_pos  107.23
2                       fraud_Lind-Buckridge  entertainment  220.11
3         fraud_Kutch, Hermiston and Farrell  gas_transport   45.00
4                        fraud_Keeling-Crist       misc_pos   41.96
...                                      ...            ...     ...
1296670                    fraud_Reichel Inc  entertainment   15.56
1296671             fraud_Abernathy and Sons    food_dining   51.70
1296672                 fraud_Stiedemann Ltd    food_dining  105.93
1296673  fraud_Reinger, Weissnat and Strosin    food_dining   74.90
1296674  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30

               first       last gender                         street  ...  \
0           Jennifer      Banks      F                 561 Perry Cove  ...
1          Stephanie       Gill      F   43039 Riley Greens Suite 393  ...
2             Edward    Sanchez      M       594 White Dale Suite 530  ...
3             Jeremy      White      M    9443 Cynthia Court Apt. 038  ...
4              Tyler     Garcia      M               408 Bradley Rest  ...
...              ...        ...    ...                            ...  ...
1296670         Erik  Patterson      M       162 Jessica Row Apt. 072  ...
1296671      Jeffrey      White      M  8617 Holmes Terrace Suite 651  ...
1296672  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  ...
1296673       Joseph     Murray      M           42933 Ryan Underpass  ...
1296674      Jeffrey      Smith      M           135 Joseph Mountains  ...

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling
1        48.8878 -118.2105       149  Special educational needs teacher
2        42.1808 -112.2620      4154        Nature conservation officer
3        46.2306 -112.1138      1939                    Patent attorney
4        38.4207  -79.4629        99     Dance movement psychotherapist
...          ...       ...       ...                                ...
1296670  37.7175 -112.4777       258                       Geoscientist
1296671  39.2667  -77.5101       100   Production assistant, television
1296672  32.9396 -105.8189       899                    Naval architect
1296673  43.3526 -102.5411      1126              Volunteer coordinator
1296674  45.8433 -113.8748       218           Therapist, horticultural

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999
...             ...                               ...         ...        ...
1296670  1961-11-24  440b587732da4dc1a6395aba5fb41669  1371816728  36.841266
1296671  1979-12-11  278000d2e0d2277d1de2f890067dcc0a  1371816739  38.906881
1296672  1967-08-30  483f52fe67fabef353d552c1e662974c  1371816752  33.619513
1296673  1980-08-18  d667cdcbadaaed3da3f4020e83591c83  1371816816  42.788940
1296674  1995-08-16  8f7c8e4ab7f25875d753b422917c98c9  1371816817  46.565983

         merch_long  is_fraud
0        -82.048315         0
1       -118.186462         0
2       -112.154481         0
3       -112.561071         0
4        -78.632459         0
...             ...       ...
1296670 -111.690765         0
1296671  -78.246528         0
1296672 -105.130529         0
1296673 -103.241160         0
1296674 -114.186110         0

[1296675 rows x 23 columns]

In [3]:
from copy import deepcopy
actual = deepcopy(df)

In [4]:
from sklearn import preprocessing
LE = preprocessing.LabelEncoder()
df['merchant'] = LE.fit_transform(df['merchant'])
df['category'] = LE.fit_transform(df['category'])
df['first'] = LE.fit_transform(df['first'])
df['last'] = LE.fit_transform(df['last'])
df['gender'] = LE.fit_transform(df['gender'])
df['street'] = LE.fit_transform(df['street'])
df['city'] = LE.fit_transform(df['city'])
df['state'] = LE.fit_transform(df['state'])
df['job'] = LE.fit_transform(df['job'])

In [6]:
print(df.head(15))

    Unnamed: 0 trans_date_trans_time            cc_num  merchant  category  \
0            0   2019-01-01 00:00:18  2703186189652095       514         8
1            1   2019-01-01 00:00:44      630423337322       241         4
2            2   2019-01-01 00:00:51    38859492057661       390         0
3            3   2019-01-01 00:01:16  3534093764340240       360         2
4            4   2019-01-01 00:03:06   375534208663984       297         9
5            5   2019-01-01 00:04:08  4767265376804500       607         2
6            6   2019-01-01 00:04:42    30074693890476       534         3
7            7   2019-01-01 00:05:08  6011360759745864       107         2
8            8   2019-01-01 00:05:18  4922710831011201       250         9
9            9   2019-01-01 00:06:01  2720830304681674       563         4
10          10   2019-01-01 00:06:23     4642894980163       543         4
11          11   2019-01-01 00:06:53   377234009633447       304        11
12          12   2019-01-01 00:06:56   180042946491150       394         4
13          13   2019-01-01 00:07:27  5559857416065248       308         4
14          14   2019-01-01 00:09:03  3514865930894695        42        12

       amt  first  last  gender  street  ...      lat      long  city_pop  \
0     4.97    162    18       0     568  ...  36.0788  -81.1781      3495
1   107.23    309   157       0     435  ...  48.8878 -118.2105       149
2   220.11    115   381       1     602  ...  42.1808 -112.2620      4154
3    45.00    163   463       1     930  ...  46.2306 -112.1138      1939
4    41.96    336   149       1     418  ...  38.4207  -79.4629        99
5    94.63    162    82       0     471  ...  40.3750  -75.2045      2158
6    44.54    199   360       0     882  ...  37.9931 -100.9893      2691
7    71.65    311   467       1     224  ...  38.8432  -78.6003      6018
8     4.27    144    70       0     685  ...  40.3359  -79.6607      1472
9   198.39    239     3       0     213  ...  36.5220  -87.3490    151785
10   24.74    114   283       1     179  ...  40.7491  -95.0380      7297
11    7.77    326    33       0     443  ...  39.3716  -77.8229      1925
12   71.22     66   368       1     347  ...  27.7898  -82.7243    341043
13   96.29    148   191       1     598  ...  41.6125 -122.5258       589
14    7.77     74    67       1     158  ...  32.9396 -105.8189       899

    job         dob                         trans_num   unix_time  merch_lat  \
0   370  1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293
1   428  1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047
2   307  1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704
3   328  1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331
4   116  1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999
5   479  1961-06-19  189a841a0a8ba03058526bcfe566aab5  1325376248  40.653382
6    29  1993-08-16  83ec1cc84142af6e2acf10c44949e720  1325376282  37.162705
7   127  1947-08-21  6d294ed2cc447d2c71c7171a3d54967c  1325376308  38.948089
8   375  1941-03-07  fc28024ce480f8ef21a32d64c93a29f5  1325376318  40.351813
9   329  1974-03-28  3b9014ea8fb80bd65de0b1463b00b00e  1325376361  37.179198
10  239  1990-07-13  d71c95ab6b7356dd74389d41df429c87  1325376383  40.275891
11  444  1966-02-14  3c74776e558f1499a7824b556e474b1d  1325376413  40.103866
12  165  1989-02-28  c1d9a7ddb1e34639fe82758de97f4abf  1325376416  27.630593
13  443  1945-12-21  413636e759663f264aae1819a4d4f231  1325376447  41.657520
14  308  1967-08-30  8a6293af5ed278dea14448ded2685fea  1325376543  32.863258

    merch_long  is_fraud
0   -82.048315         0
1  -118.186462         0
2  -112.154481         0
3  -112.561071         0
4   -78.632459         0
5   -76.152667         0
6  -100.153370         0
7   -78.540296         0
8   -79.958146         0
9   -87.485381         0
10  -96.011548         0
11  -78.624459         0
12  -82.308891         0
13 -122.230347         0
14 -106.520205         0

[15 rows x 23 columns]

In [7]:
numeric_df = df.select_dtypes(include=['float64', 'int64'])
correlation = numeric_df.corr(method='pearson')
correlation

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
Unnamed: 0,1.000000,0.000386,-0.000251,0.000709,0.000602,-0.000676,-0.001678,0.998971,0.000541,-0.000671,-0.004767
cc_num,0.000386,1.000000,0.001769,0.041459,-0.059271,-0.048278,-0.008991,0.000354,-0.058942,-0.048252,-0.000981
amt,-0.000251,0.001769,1.000000,0.001843,-0.001926,-0.000187,0.005818,-0.000293,-0.001873,-0.000151,0.219404
zip,0.000709,0.041459,0.001843,1.000000,-0.114290,-0.909732,0.078467,0.000670,-0.113561,-0.908924,-0.002162
lat,0.000602,-0.059271,-0.001926,-0.114290,1.000000,-0.015533,-0.155730,0.000632,0.993592,-0.015509,0.001894
long,-0.000676,-0.048278,-0.000187,-0.909732,-0.015533,1.000000,-0.052715,-0.000642,-0.015452,0.999120,0.001721
city_pop,-0.001678,-0.008991,0.005818,0.078467,-0.155730,-0.052715,1.000000,-0.001714,-0.154781,-0.052687,0.002136
unix_time,0.998971,0.000354,-0.000293,0.000670,0.000632,-0.000642,-0.001714,1.000000,0.000561,-0.000635,-0.005078
merch_lat,0.000541,-0.058942,-0.001873,-0.113561,0.993592,-0.015452,-0.154781,0.000561,1.000000,-0.015431,0.001741
merch_long,-0.000671,-0.048252,-0.000151,-0.908924,-0.015509,0.999120,-0.052687,-0.000635,-0.015431,1.000000,0.001721
is_fraud,-0.004767,-0.000981,0.219404,-0.002162,0.001894,0.001721,0.002136,-0.005078,0.001741,0.001721,1.000000

In [8]:
sort = correlation.iloc[-1,:].sort_values(ascending = True)
sort

unix_time    -0.005078
Unnamed: 0   -0.004767
zip          -0.002162
cc_num       -0.000981
long          0.001721
merch_long    0.001721
merch_lat     0.001741
lat           0.001894
city_pop      0.002136
amt           0.219404
is_fraud      1.000000
Name: is_fraud, dtype: float64

In [9]:
drop = ['Unnamed: 0','trans_date_trans_time','first','last','zip','lat','long','city_pop','dob','trans_num','unix_time','merch_long','merch_lat','amt','is_fraud']
data = df.drop(columns = drop)
data

,cc_num,merchant,category,gender,street,city,state,job
0,2703186189652095,514,8,0,568,526,27,370
1,630423337322,241,4,0,435,612,47,428
2,38859492057661,390,0,1,602,468,13,307
3,3534093764340240,360,2,1,930,84,26,328
4,375534208663984,297,9,1,418,216,45,116
...,...,...,...,...,...,...,...,...
1296670,30263540414123,499,0,1,154,330,44,215
1296671,6011149206456997,2,1,1,856,813,20,360
1296672,3514865930894695,599,1,1,158,346,32,308
1296673,2720012583106919,509,1,1,433,471,41,485
1296674,4292902571056973207,370,1,1,127,782,26,467

In [10]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [11]:
Rand_forst_class = RandomForestClassifier(n_estimators=100,max_depth=15,random_state=0)
pred=Rand_forst_class.fit(x,y)

In [13]:
test_data = pd.read_csv("C:/Users/mail2/Desktop/Sharli/datasets/fraudTest.csv")
test_data

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [14]:
columns_drop = ['Unnamed: 0','trans_date_trans_time','first','last','zip','lat','long','city_pop','dob','trans_num','unix_time','merch_long','merch_lat','amt','is_fraud']
test = test_data.drop(columns=columns_drop)
test

,cc_num,merchant,category,gender,street,city,state,job
0,2291163933867244,fraud_Kirlin and Sons,personal_care,M,351 Darlene Green,Columbia,SC,Mechanical engineer
1,3573030041201292,fraud_Sporer-Keebler,personal_care,F,3638 Marsh Union,Altonah,UT,"Sales professional, IT"
2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,F,9333 Valentine Point,Bellmore,NY,"Librarian, public"
3,3591919803438423,fraud_Haley Group,misc_pos,M,32941 Krystal Mill Apt. 552,Titusville,FL,Set designer
4,3526826139003047,fraud_Johnston-Casper,travel,M,5783 Evan Roads Apt. 465,Falmouth,MI,Furniture designer
...,...,...,...,...,...,...,...,...
555714,30560609640617,fraud_Reilly and Sons,health_fitness,M,558 Michael Estates,Luray,MO,Town planner
555715,3556613125071656,fraud_Hoppe-Parisian,kids_pets,M,572 Davis Mountains,Lake Jackson,TX,Futures trader
555716,6011724471098086,fraud_Rau-Robel,kids_pets,F,144 Evans Islands Apt. 683,Burbank,WA,Musician
555717,4079773899158,fraud_Breitenberg LLC,travel,M,7020 Doyle Stream Apt. 951,Mesa,ID,Cartographer
555718,4170689372027579,fraud_Dare-Marvin,entertainment,M,830 Myers Plaza Apt. 384,Edmond,OK,Media buyer

In [15]:
xtest = data.iloc[:,:-1]
ytest = data.iloc[:,-1]

In [ ]:
prediction = Rand_forst_class.predict(xtest)
prediction
acc = accuracy_score(ytest,prediction)
print(f"Accuracy: {acc:}")